# services that are overriden during tests
services:

    # default configuration for services in *this* file
    _defaults:
        public: true
        
    App\Tests\Fixtures\:
        resource: '../tests/Fixtures/*'

    App\Http\ClientFactory:
        alias: App\Tests\Fixtures\Http\ClientFactory

    App\Http\MailboxFactory:
        alias: App\Tests\Fixtures\Mail\MailboxFactory

    App\Mail\InboxReader:
        class: App\Tests\Fixtures\Mail\InboxReader
        arguments:
          - "%env(MAIL_PAYMENT_HOST)%"
          - "%env(MAIL_PAYMENT_LOGIN)%"
          - "%env(MAIL_PAYMENT_PASSWORD)%"
          
    App\Reference\ReferenceGenerator:
        alias: App\Tests\Fixtures\Reference\SequentialReferenceGenerator

    App\Airbnb\AirbnbBot:
        arguments:
            # I wanted to specifiy only the $log = false but getting an error "argument 1 must be defined before. Check your service definition."
            - '@doctrine'
            - '@App\Http\ClientFactory'
            - '@App\Mail\MailboxFactory'
            - '@App\Reference\ReferenceGenerator'
            - false
     
    App\Airbnb\AirbnbReservationBot:
        arguments:
            # I wanted to specifiy only the $log = false but getting an error "argument 1 must be defined before. Check your service definition."
            - '@doctrine'
            - '@App\Mail\InboxReader'
            - true